### ISSUE TITLE
Clojurescript portable

### ISSUE THREAD

**Issue by viebel** [jiacai2050/scheme.clj#1]
Could you make it clojurescript portable?
Then I will be able to add it as a client side evaluator to KLIPSE https://github.com/viebel/klipse

Also, you will be able to write a blog post about your lib with embedded interactive code snippets.

**Comment by jiacai2050** [comment]
Sounds interesting to me.

 I will dip my toe into clojurescript and make it out ASAP .

**Comment by viebel** [comment]
There is 1st draft of a guide here:
https://github.com/viebel/klipse/wiki/How-to-make-a-clojure-library-self-host-compatible

**Comment by jiacai2050** [comment]
Hi @viebel , I have ported this project to ClojureScript, but the lib [core.match](https://github.com/clojure/core.match) on which this project depends  [doesn't support self-host](https://github.com/mfikes/planck/issues/364), so I think this project can't be a client to klipse.

**Comment by viebel** [comment]
So bad :(

**Comment by viebel** [comment]
I've been working on a port of `core.match` to be self-host compatible.
Now, we can run your scheme evaluator in the browser with klipse. See http://bit.ly/2dRk31C

Now you can write a blog post about your scheme evaluator with interactive code snippets.

PS: There is  JIRA ticket for core.match self-host compatible: http://dev.clojure.org/jira/browse/MATCH-116. Please vote for it!

**Comment by viebel** [comment]
Good news! core.match is now self-host compatible.
I have created a fork with the necessary changes -
https://github.com/viebel/core.match
Could you give it a try with `scheme.clj` - all you need to to is to add
the `external-libs` url parameter like this:
http://app.klipse.tech/?cljs_in.gist=viebel/10da8338c4a1573fab8c04989e471704&external-libs=%5Bhttps%3A%2F%2Fraw.githubusercontent.com%2Fviebel%2Fcore.match%2Fmaster%2Fsrc%2Fmain%2Fclojure%2F%5D

**Comment by jiacai2050** [comment]
https://github.com/jiacai2050/scheme.clj/wiki/Run-Scheme-in-Clojure

Is this blog OK ?

**Comment by viebel** [comment]
Yeah.  But it doesn't have any interactive snippet!

**Comment by jiacai2050** [comment]
I have some kinds of questions here.

I have read doc [here](https://github.com/viebel/klipse#scheme), Is this to say I should compile my project to a single js file, and then to include it like the doc does ?

**Comment by viebel** [comment]
No.

You just need to use `data-external-libs` on the first snippet of your blog post. 

Take a look at the source page of [this article](http://blog.klipse.tech/clojure/2016/10/25/core-match.html) for instance.

**Comment by jiacai2050** [comment]
I have followed your article to write a new blog

http://liujiacai.net/scheme.clj/

But, there are still some errors in console

![image](https://cloud.githubusercontent.com/assets/3848910/19938134/d233c8f8-a15e-11e6-959e-16f5c4b8cdb6.png)

Is anything I am missing ?

**Comment by viebel** [comment]
You are almost there :)
1. You have to put the 3 parts of the klipse tag  (css, settings, script) at the end of the body.
2. It's better to load klipse over `https` - pay attention it's a different url
3. the settings must be before the script tag like this:

``` html
<link rel="stylesheet" type="text/css" href="https://storage.googleapis.com/app.klipse.tech/css/codemirror.css">

<script>
    window.klipse_settings = {
        selector: '.language-klipse'// css selector for the html elements you want to klipsify
    };
</script>
<script src="https://storage.googleapis.com/app.klipse.tech/plugin/js/klipse_plugin.js"></script>
```

**Comment by jiacai2050** [comment]
Thanks ! It works now 🍺

**Comment by viebel** [comment]
That's wonderful!

Congratulations !!

One last thing: Instead of of snippet with `(map eval ...)`, I would write several snippets with an introductory text for each one.

Makes sense?

**Comment by jiacai2050** [comment]
In [Live Demo](http://liujiacai.net/scheme.clj/#live-demo) part, I have already written different snippet for different feature. Is this OK ?
@viebel
